# Generated by Django 5.1.2 on 2024-12-08 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletters',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='newsletter/'),
        ),
    ]