# Generated by Django 5.1.2 on 2024-12-08 12:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_alter_newsletters_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletters',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='newsletters',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='newsletters',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='subscribetonewsletter',
            name='date_added',
        ),
        migrations.AddField(
            model_name='newsletters',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscribetonewsletter',
            name='date_subscribed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='subscribetonewsletter',
            name='newsletter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newsletter.newsletters'),
        ),
        migrations.AlterField(
            model_name='newsletters',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newsletters',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='newsletter_images/'),
        ),
        migrations.AlterField(
            model_name='subscribetonewsletter',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
