# Generated by Django 5.1.2 on 2024-12-13 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_alter_subscribetonewsletter_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribetonewsletter',
            name='user',
        ),
    ]
