# Generated by Django 5.1.2 on 2024-12-13 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscribeToNewsletter',
        ),
    ]
