# Generated by Django 5.1.4 on 2025-02-17 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productreview_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
